site_name: typingjson
site_description: Interoperates @dataclass with json objects


theme:
    name: 'material'
    palette:
      primary: 'black'
      accent: 'grey'
    logo: 'typingjson-white.svg'
    favicon: 'favicon.png'

repo_name: dutradda/typingjson
repo_url: https://github.com/dutradda/typingjson
edit_uri: ''
google_analytics:
    - ''
    - 'auto'

nav:
    - typingjson: 'index.md'
    - Features: 'features.md'
    - Python dataclass intro: 'python-dataclass.md'
    - Json intro: 'json.md'
    - Tutorial - User Guide:
        - Introduciton: 'tutorial/intro.md'
        - Choose Input Fields to Parse: 'tutorial/choose-fields-parse.md'
        - Omit fields on Output: 'tutorial/omit-fields-output.md'
        - Custom Data Types: 'tutorial/custom-data-types.md'
        - Disable Input Parsing: 'tutorial/disable-input-parsing.md'
        - Custom Json Serializer: 'tutorial/custom-json-serializer.md'
    - Alternatives, Inspiration and Comparisons: 'alternatives.md'
    - Benchmarks: 'benchmarks.md'
    - Help typingjson - Get Help: 'help.md'
    - Development - Contributing: 'contributing.md'
    - Changelog: changelog.md

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: docs
  - admonition
  - codehilite
  - extra
